# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_account_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='phone_no',
            field=models.CharField(max_length=25),
        ),
    ]
